### ISSUE TITLE
Nice project. But my humble opinion is that the architecture of the project is a bit wrong.

### ISSUE THREAD

**Issue by demirmusa** [Nebula-Software-Systems/Nebula.Caching#1]
Hi. I just saw your document on dev.to. I think it's a nice project. I hope it gets where you want it to go. However, in my humble opinion, the architecture of the project is a bit off. Currently, your project doesn't have any solution file and is a single project only built on Redis. You need to create a solution and split your project into several different ones.

For example, initially, you need two projects: **Nebula.Caching.Core** and **Nebula.Caching.RedisCache**:
![Nebula Caching1](https://github.com/Nebula-Software-Systems/Nebula.Caching/assets/48536631/4354041c-24f0-4a50-ba17-6579e8f69ece)

**Nebula.Caching.Core:** This is a core project where you have all of your interfaces and all caching system-independent DTOs. And the core mechanics.
**Nebula.Caching.RedisCache:** This is a project that contains all things related to Redis. Caching, key generations, etc. It has **Nebula.Caching.Core** reference and all necessary implementations of the interfaces that you defined in the core project.
So your core code will work independently of caching over interfaces.
Then you can release **Nebula.Caching.RedisCache** nuget package and users can use your library with redis.

After that, when you want to implement more libraries, caching systems you can easily implement them in your system by adding another project to your solution. The new caching systems will also just implement the caching stuff and all necessary interfaces comes from core project and your code will work with the new caching system.
For example:
![Nebula Caching2](https://github.com/Nebula-Software-Systems/Nebula.Caching/assets/48536631/4ff2f512-ba51-492b-b92b-43de143473e7)
After that, users who want to use Redis can use the system by adding the **Nebula.Caching.RedisCache** NuGet package to their projects, and users who want to use in-memory cache can use the system by adding the **Nebula.Caching.InMemory** NuGet package to their projects.

**Comment by RafaelJCamara** [comment]
Hello there!

First of all, thank you so much for dropping by and leaving this feedback! It means a lot to me!

You are right on your assessment!

The project needs to eventually migrate to a state where each Cache provider should be its own Nuget package, for sure.

My intention for now was to test things out and see the flow of this all Open-Source world and Nuget distribution, which led me to do some bad choices, like the ones you mentioned!

If you like the project, please consider give it a nice little star!

Have a great rest of your week!
